### PR TITLE
add SCO url, domain-name, ipv4-addr

### PR DESCRIPTION
**Pull request by jaysneg**
add validators and tests

### CODE REVIEW

**Comment by jaysneg** [comment]
@jordan2175 could you please review

**Comment by jordan2175** [comment]
Yes, I will


Thanks,
Bret
PGP Fingerprint: 63B4 FC53 680A 6B7D 1447  F2C0 74F8 ACAE 7415 0050
"Without cryptography vihv vivc ce xhrnrw, however, the only thing that can not be unscrambled is an egg."

**Comment by jordan2175** [comment]
Thanks for the pull requests. I will give you public credit in the readme and the individual files if you would like, but not on the copyright line. I need things to be very un-encumbered to make it easy for people to know what they can and can not do with this code.

**Comment by jordan2175** [comment]
And I think I would prefer the directory / package name to just be the STIX object name without the trailing object.

**Comment by jaysneg** [comment]
> And I think I would prefer the directory / package name to just be the STIX object name without the trailing object.

ok

**Comment by jaysneg** [comment]
> Thanks for the pull requests. I will give you public credit in the readme and the individual files if you would like, but not on the copyright line. I need things to be very un-encumbered to make it easy for people to know what they can and can not do with this code.

OK, it wasn't clear what I was supposed to put there, so just tried to follow the pattern

**Comment by jaysneg** [comment]
> And I think I would prefer the directory / package name to just be the STIX object name without the trailing object.

For SCO better add Object at name or add all STIX objects to STIX namespace or we will have issues with names

At SCO STIX contains url object and GO lang have [url](https://golang.org/pkg/net/url/)

**Comment by jaysneg** [comment]
> And I think I would prefer the directory / package name to just be the STIX object name without the trailing object.

and at docs it have Object in naming [https://docs.oasis-open.org/cti/stix/v2.1/csprd01/stix-v2.1-csprd01.html#_Toc16070687](https://docs.oasis-open.org/cti/stix/v2.1/csprd01/stix-v2.1-csprd01.html#_Toc16070687)

**Comment by jordan2175** [comment]
So if I accept this pull request and immediately change it and push an update, are you okay with that?  And yes, there will be some issues with some objects that conflict with go.  But I think we can tackle them on a case-by-case basis.   i just would like this library to follow the STIX 2.1 spec as closely as possible.

**Comment by jaysneg** [comment]
@jordan2175 ok

**Pull request merged**
