### PR TITLE
Add infrastructure setters and validations

### PR DESCRIPTION
**Pull request by jaysneg**

### CODE REVIEW

**Comment by jaysneg** [comment]
@jordan2175 could you please review this PR

**Comment by jordan2175** [comment]
Thanks for the pull requests.  I will give you public credit in the readme and the individual files if you would like, but not on the copyright line.  I need things to be very un-encumbered to make it easy for people to know what they can and can not do with this code.

**Comment by jaysneg** [comment]
@jordan2175 OK, it wasn't clear what I was supposed to put there, so just tried to follow the pattern

**Comment by jordan2175** [comment]
So if I accept this pull request and immediately change it and push an update, are you okay with that?

**Comment by jordan2175** [comment]
@jaysneg Please verify on this pull request if you are okay with me accepting the pull request but then removing your copyright line.

**Comment by jaysneg** [comment]
> Please verify on this pull request if you are okay with me accepting the pull request but then removing your copyright line.

ok

**Pull request merged**
